Use accountURL instead of collectionURL
When using a collectionURL, the sample will simply not work. Even worse, it will blow up with:

```
node main.js
TypeError: Cannot read property 'value' of undefined
    at restClient.options.then (/Users/joao/Work/vsts-build-status/node_modules/vso-node-api/VsoClient.js:130:60)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

It seems that the right thing to do here is to use the account URL instead.